### ISSUE TITLE
unknow property of signing.filepath in build.gradle

### ISSUE THREAD

**Issue by ziyannchen** [netless-io/flat-android#3]
Hi, thx for the maintenance of this nice project. I'm just a beginner in android development and I'm just exploring flat.
After I download this project and open it with my Android Studio Bumblebee | 2021.1.1, there is an error presented as follows:

**org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'signing.filepath' for project ':app' of type org.gradle.api.Project.**

I think it comes from the build.gradle file in the signingConfig:
```
signingConfigs {
      release {
          storeFile file(property('signing.filepath'))
          storePassword property('signing.storePassword')
          keyAlias property('signing.keyAlias')
          keyPassword property('signing.keyPassword')
      }

      debug {
          storeFile file(property('signing.filepath'))
          storePassword property('signing.storePassword')
          keyAlias property('signing.keyAlias')
          keyPassword property('signing.keyPassword')
      }
  }
```
Is this an OAuth setting for Wechat loggin? There seems to be a little bit less information about set up on android than on the web.
Really hope the flat to have a wider influence in the future.
Best regards.

**Comment by aderan** [comment]
Thank you for your attention
As you guessed, WeChat login requires a specific signature file. The file is somewhat private for now.
But as an open source app, it does need to be quick for devlopers to run to see how it works, and we've made some fixes for this to handle the lack of a signature file. commited as  [06811c](https://github.com/netless-io/flat-android/commit/06811c81e24321b822eb279106d8a7dbb23576ae)

Best regards.

**Comment by ziyannchen** [comment]
OKay! Then thanks for this new commit.
